version: '3'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - "./MySQL:/docker-entrypoint-initdb.d"
  server:
    build:
      context: ./Go/server
    volumes:
      - "./Go/server:/go/tmp/src/server"
    command: "go run /go/tmp/src/server/server.go"
    container_name: golang_server
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
  client:
    build:
      context: ./Go/client
    volumes:
      - "./Go/client:/go/tmp/src/client"
    command: "go run /go/tmp/src/client/client.go"
    container_name: golang_client
    ports:
      - "9090:9090"
    tty: true
    depends_on:
      - server
  frontend:
    build:
      context: ./Go/frontend
      dockerfile: Dockerfile
    command: "npm start"
    container_name: frontend
    volumes:
      - './Go/frontend:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
